### PR TITLE
add replitPackages.processing4

### PR DESCRIPTION
**Pull request by cdmistman**
educators have been using a legacy [processing4](https://replit.com/@demcrepl/Processing4?v=1) template for teaching, but the version of processing in current stable channels is <= processing 3. This adds it to the overlay as an effective backport

### CODE REVIEW

**Comment by masad-frost** [comment]
Can't we get it from maven?

**Comment by cdmistman** [comment]
maybe, right now the [official template](https://replit.com/@replit/Processing-Java?v=1) uses maven but only consumes processing as a library, not as a JVM language. I'll look into getting it to run via maven, otherwise this bug won't be fixed until the next cacache rollout.

**Comment by cdmistman** [comment]
upon further research, it seems the maintainers of processing4 really wish the unofficial maven release didn't exist, as it's caused confusion and results in support requests that they can't afford to dig into https://github.com/processing/processing4/issues/262

i'm gonna again look into getting the existing processing4 directory (ie, from the legacy template) working post-migration, but i still think this should exist in our nixpkgs so teachers can use a truly-nix template for this (instead of using processing4 as a library, as our current official template suggests to do)

**Comment by cdmistman** [comment]
upon further research, i think it's too complicated to get this working without just making a nixpkg. i'm wary of maintenance burden, but once 23.05 is released we should be in a better state

**Review by airportyh — APPROVED** [review]
Tarring ffmpeg was intense!

**Pull request merged**
