### PR TITLE
Runner priority

### PR DESCRIPTION
**Pull request by airportyh**
# Why?

Add runner priority field to allow a module to prefer some runners vs others. This came up in the C and C++ modules where multiple runners can be applicable at the same time, but there isn't a way to specify one vs the other and the result came down to chance. And for users that don't have `flag-toolchain-multiple-runners`, they won't have a way to switch the runner if we got it wrong.

## Changes

Added a priority field to runners. Lower means higher. The plan is to have `.replit/interp` at 0 and `.replit/run` at 1, and then any priority set in a Nix module should be 1 or greater. If priority is not set, it means infinity.

### CODE REVIEW

**Comment by cdmistman** [comment]
please add in the PR description that this is a change that is not-forwards-compatible and requires reversions in repl-it-web and goval before this work can be reverted

**Comment by cdmistman** [comment]
are we sure this is the right solution here? we're adding the feature to the site that gates the beta templates to users with a certain LD flag. why not gate it to the same `flag-toolchain-multiple-runners` flag since that's the intended experience?

also, imo there shouldn't be negative numbers, that should be reserved for user module overrides. `.replit/interp` should be 0, `.replit/run` should be 1, and module runners should be 2+

**Comment by airportyh** [comment]
> please add in the PR description that this is a change that is not-forwards-compatible and requires reversions in repl-it-web and goval before this work can be reverted

I think reverting this should not break goval/repl-it-web, because the field is optional.

**Comment by airportyh** [comment]
> are we sure this is the right solution here? we're adding the feature to the site that gates the beta templates to users with a certain LD flag. why not gate it to the same `flag-toolchain-multiple-runners` flag since that's the intended experience?

You mean gate the use of the priority field? Or you mean an different solution?

> also, imo there shouldn't be negative numbers, that should be reserved for user module overrides. `.replit/interp` should be 0, `.replit/run` should be 1, and module runners should be 2+

ok.

**Comment by cdmistman** [comment]
> You mean gate the use of the priority field in goval / repl-it-web? Or you mean an different solution altogether?

i mean, why don't we gate the nix modules templates to only those with the ability to select the runner from the dropdown? we don't need priorities if everyone can just select the runner right?

**Comment by airportyh** [comment]
> > You mean gate the use of the priority field in goval / repl-it-web? Or you mean an different solution altogether?
> 
> i mean, why don't we gate the nix modules templates to only those with the ability to select the runner from the dropdown? we don't need priorities if everyone can just select the runner right?

I'd rather not have the rollout of Nix modules be dependent on the multi-runner feature. I view them as orthogonal. Also, the multi-run feature is only a small part of what Nix modules provide.

**Pull request merged**
